import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import design from "../public/design.png";
import code from "../public/code.png";
import android from "../public/android.png";
import profilePic from "../public/profile-pic.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Abdo Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white dark:bg-gray-900 px-10 pb-20 md:px-20 lg:px-40 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between  dark:text-white">
            <h1 className=" text-xl font-burtons">Abdomo .. dev</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="../resume-website.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-7xl  dark:text-teal-400">
              Abderrahmane Moussaoui
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Web3 Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-lg :text-xl max-w-lg mx-auto">
              To work as a
              <span className="font-semibold"> Software Engineer</span> in a
              community where I can utilize my skills and knowledge related to
              <span className="font-semibold"> web3 development</span> and
              develop robust dapps, protocols, and NFTs.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/moussaoui91/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/abdoMous">
              <AiFillGithub />
            </a>
            <a href="https://twitter.com/moussaoui91">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.instagram.com/abdomooo/">
              <AiFillInstagram />
            </a>
          </div>
          <div className=" relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={profilePic} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a Software Developer, I built
              several apps for me and for startups and collaborated with
              talanted people to make it accesible and easy to use.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-800 dark:text-white">
              <Image src={code} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">Web3</h3>
              <p>
                Creating well unit-tested smart contracts for any EVM
                blockchains
              </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className=" text-gray-800 dark:text-white py-1 ">Solidity</p>
              <p className=" text-gray-800 dark:text-white py-1">Hardhat</p>
              <p className=" text-gray-800 dark:text-white py-1">Ethers.js</p>
              <p className=" text-gray-800 dark:text-white py-1">Moralis</p>
              <p className=" text-gray-800 dark:text-white py-1">IPFS</p>
              <p className=" text-gray-800 dark:text-white py-1">thegraph</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10  dark:bg-slate-800 dark:text-white">
              <Image src={design} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">Web2</h3>
              <p>Creating easy to use web apps that interacts with dapps</p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className=" text-gray-800 dark:text-white py-1">React</p>
              <p className=" text-gray-800 dark:text-white py-1">Firebase</p>
              <p className=" text-gray-800 dark:text-white py-1">Next.js</p>
              <p className=" text-gray-800 dark:text-white py-1">Tailwindcss</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10  dark:bg-slate-800 dark:text-white">
              <Image src={android} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">Android</h3>
              <p>Creating ready-to-publish native android apps</p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className=" text-gray-800 dark:text-white py-1">Java</p>
              <p className=" text-gray-800 dark:text-white py-1">
                Android Studio
              </p>
              <p className=" text-gray-800 dark:text-white py-1">Firebase</p>
              <p className=" text-gray-800 dark:text-white py-1">
                Material Design
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
