import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import profilePic from "../public/profile-pic.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Abdo Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white dark:bg-gray-900 px-10 pb-20 md:px-20 lg:px-40 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between  dark:text-white">
            <h1 className=" text-xl font-burtons">Abdomo .. dev</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="../resume-website.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-7xl  dark:text-teal-400">
              Abderrahmane Moussaoui
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Web3 Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-lg :text-xl max-w-lg mx-auto">
              To work as a
              <span className="font-semibold"> Software Engineer</span> in a
              community where I can utilize my skills and knowledge related to
              <span className="font-semibold"> web3 development</span> and
              develop robust dapps, protocols, and NFTs.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/moussaoui91/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/abdoMous">
              <AiFillGithub />
            </a>
            <a href="https://twitter.com/moussaoui91">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.instagram.com/abdomooo/">
              <AiFillInstagram />
            </a>
          </div>
          <div className=" relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={profilePic} layout="fill" objectFit="cover" />
          </div>
        </section>
      </main>
    </div>
  );
}
